# Activity 5.1 Text Similarity

## Objective(s):

This activity aims to introduce how to implement text similarity

## Intended Learning Outcomes (ILOs):
* Demonstrate how to remove special characters from text
* Demonstrate how to measure text simiarity using distance
* Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

## Resources:
* Jupyter Notebook
* songdata.csv

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Procedures
Load the necessary libraries

In [ ]:
import nltk
import pandas as pd
import os

In [ ]:
data_path = '/content/drive/My Drive/Colab Notebooks/Dataset'
data = pd.read_csv(os.path.join(data_path, 'songdata.csv'))
data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \nAnd..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \nTouch me gentl..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \nWhy I had t...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

Find the lyrics by the artist The Beatles

In [ ]:
beatles = data[data.artist=='The Beatles']
beatles.head()

,artist,song,link,text
1198,The Beatles,A Shot Of Rhythm And Blues,/b/beatles/a+shot+of+rhythm+blues_20014867.html,"Well, if your hands start a-clappin' \nAnd yo..."
1199,The Beatles,Across The Universe,/b/beatles/across+the+universe_10026507.html,Words are flowing out like \nEndless rain int...
1200,The Beatles,All I've Got To Do,/b/beatles/all+ive+got+to+do_10026646.html,"Whenever I want you around, yeah \nAll I gott..."
1201,The Beatles,And I Love Her,/b/beatles/and+i+love+her_10026463.html,I give her all my love \nThat's all I do \nA...
1202,The Beatles,And Your Bird Can Sing,/b/beatles/and+your+bird+can+sing_10026364.html,You tell me that you've got everything you wan...

Check the number of Beatles songs in the data set

In [ ]:
data.artist.value_counts().loc[['The Beatles']]

artist
The Beatles    178
Name: count, dtype: int64

Take a look at the first song's lyrics

In [ ]:
beatles.iloc[0,3]

"Well, if your hands start a-clappin'  \nAnd your fingers start a-poppin'  \nAnd your feet start a-movin' around  \nAnd if you start to swing and sway  \n  \nWhen the band starts to play  \nA real cool way out sound  \nAnd if you get to can't help it and you can't sit down  \nYou feel like you gotta move around  \n  \nYou get a shot of rhythm and blues.  \nWith just a little rock and roll on the side  \nJust for good measure.  \nGet a pair of dancin' shoes  \n  \nWell, with your lover by your side  \nDon't you know you're gonna have a rockin' time, see'mon!  \nDon't you worry 'bout a thing  \nIf you start to dance and sing  \n  \nAnd chills come up on you  \nAnd if the rhythm finally gets you and the beat gets you too  \nWell, here's something for you to do  \n  \nGet a shot of rhythm and blues  \nWith just a little rock and roll on the side  \nJust for good measure  \nGet a pair of dancin' shoes  \n  \nWell, with your lover by your side  \nDon't you know you're gonna have a rockin' time, see'mon!  \nDon't you worry 'bout a thing  \nIf you start to dance and sing  \n  \nAnd chills come up on you  \nAnd if the rhythm finally gets you and the beat gets you too  \nWell, here's something for you to do  \n  \nGet a shot of rhythm and blues  \nGet a pair of dancin' shoes  \nGet a shot of rhythm and blues  \nWell, with your lover by your side  \n  \nDon't you know you're gonna have a rockin' time, see'mon!  \nDon't you worry 'bout a thing  \nIf you start to dance and sing  \nAnd chills come up on you  \n  \nAnd if the rhythm finally gets you and the beat gets you too  \nWell, here's something for you to do  \nWell, here's something for you to do  \nWell, here's something for you to do\n\n"

Remove characters from the lyrics

In [ ]:
import re

newline = lambda x: re.sub(r'\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub(r'\w*\d\w*', ' ', x) # remove alphanumeric words

corpus = beatles.text.map(newline).map(alphanumeric)
corpus.head()

1198    Well, if your hands start a-clappin'   And you...
1199    Words are flowing out like   Endless rain into...
1200    Whenever I want you around, yeah   All I gotta...
1201    I give her all my love   That's all I do   And...
1202    You tell me that you've got everything you wan...
Name: text, dtype: object

Create a document term matrix using Count Vectorizer with the stop words turned on to English

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X, columns=cv.get_feature_names_out()).set_index(beatles.song)
dt.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Across The Universe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
All I've Got To Do,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
And I Love Her,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
And Your Bird Can Sing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Set display options so that the lyrics aren't cut off

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \nIt's easy if you try  \nNo hell below us  \nAbove us only sky  \nImagine all the people  \nLiving for today...  \n  \nImagine there's no countries  \nIt isn't hard to do  \nNothing to kill or die for  \nAnd no religion too  \nImagine all the people  \nLiving life in peace...  \n  \nYou may say I'm a dreamer  \nBut I'm not the only one  \nI hope someday you'll join us  \nAnd the world will be as one  \n  \nImagine no possessions  \nI wonder if you can  \nNo need for greed or hunger  \nA brotherhood of man  \nImagine all the people  \nSharing all the world...  \n  \nYou may say I'm a dreamer  \nBut I'm not the only one  \nI hope someday you'll join us  \nAnd the world will live as one\n\n
Name: text, dtype: object

Imagine lyrics in Count Vectorizer form

In [ ]:
imagine = list(dt.loc['Imagine'])
imagine[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Define the cosine similarity calculation

In [ ]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

Calculate all similarities and sort by the most similar

In [ ]:
similarity = [cosine(imagine, song) for song in X]
sorted(list(zip(similarity, beatles.song)), reverse=True)[1:6]

[(np.float64(0.22757944185316942), "I'll Cry Instead"),
 (np.float64(0.1738270040532526), 'In My Life'),
 (np.float64(0.16574838603294895), 'Eleanor Rigby'),
 (np.float64(0.1490280831849844), 'In Spite Of All The Danger'),
 (np.float64(0.14592261028699943), 'All My Loving')]

Create the TF-IDF Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Calculate all similarities and sort by the most similar using the TF-IDF data

In [ ]:
similarity_tfidf = [cosine(imagine, song) for song in X_tfidf]
sorted(list(zip(similarity_tfidf, beatles.song)), reverse=True)[1:6]

[(np.float64(0.19266277925834221), "I'll Cry Instead"),
 (np.float64(0.18004423848592196), "I'll Get You"),
 (np.float64(0.1551371744116933), 'Eleanor Rigby'),
 (np.float64(0.15054395512050195), 'In My Life'),
 (np.float64(0.12306875209548622), 'Love Of The Loved')]

Compare the lyrics of Imagine and I'll Cry Instead

In [ ]:
# Imagine lyrics
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \nIt's easy if you try  \nNo hell below us  \nAbove us only sky  \nImagine all the people  \nLiving for today...  \n  \nImagine there's no countries  \nIt isn't hard to do  \nNothing to kill or die for  \nAnd no religion too  \nImagine all the people  \nLiving life in peace...  \n  \nYou may say I'm a dreamer  \nBut I'm not the only one  \nI hope someday you'll join us  \nAnd the world will be as one  \n  \nImagine no possessions  \nI wonder if you can  \nNo need for greed or hunger  \nA brotherhood of man  \nImagine all the people  \nSharing all the world...  \n  \nYou may say I'm a dreamer  \nBut I'm not the only one  \nI hope someday you'll join us  \nAnd the world will live as one\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='I\'ll Cry Instead'].text

24774    I've got every reason on earth to be mad  \n'Cause I just lost the only girl I had  \nIf I could get my way  \nI'd get myself locked up today  \nBut I can't, so I'll cry instead  \n  \nI've got a chip on my shoulder that's bigger that my feet  \nI can't talk to people that I meet  \nIf I could see you now  \nI'd try to make you sad somehow  \nBut I can't, so I'll cry instead  \n  \nDon't want to cry when there's people there  \nI get shy when they start to stare  \nI'm gonna hide myself away  \nBut I'll come back again someday  \n  \nAnd when you do you'd better hide all the girls  \nI'm gonna break their hearts all round the world  \nYes, I'm gonna break them in two  \nAnd show you what your lovin' man can do  \nUntil then I'll cry instead\n\n
Name: text, dtype: object

### Question: Compare the two lyrics based on the output

> Based on the two object output of the I'll cry instead and Imagine lyrics by Beatle, both lyrics have a very different theme. Imagine is about Worldly Issues while I'll cry instead is about Romance. The common thing between them is that they both use a newline command which can be removed for a cleaner data.

Find the two Beatles songs that are the most similar
* Using Count Vectorizer
* Using TF-IDF Vectorizer

Calculate the cosine similarity between all combinations of documents

In [ ]:

from itertools import combinations

pairs = list(combinations(beatles.song.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(beatles)), 2)) # all index combos starting with (0,1)
song_pairs = [(beatles.song[a_index], beatles.song[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('A Shot Of Rhythm And Blues', 'Across The Universe'),
 ('A Shot Of Rhythm And Blues', "All I've Got To Do"),
 ('A Shot Of Rhythm And Blues', 'And I Love Her'),
 ('A Shot Of Rhythm And Blues', 'And Your Bird Can Sing'),
 ('A Shot Of Rhythm And Blues', 'Another Girl')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [ ]:

results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8548876342047523), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.8359173188630292),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.8058125835571367), ('And I Love Her', 'Love Me Do')),
 (np.float64(0.7930110315846619), ('If I Fell', 'Love Me Do')),
 (np.float64(0.7478391382739419), ('And I Love Her', 'All You Need Is Love'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [ ]:

results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8717047783261523),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.6599353568343105), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.6502842517883831), ('Have A Banana!', 'Crinsk Dee Night')),
 (np.float64(0.6232797327325461), ("Don't Let Me Down", 'Let It Be')),
 (np.float64(0.5275364336322863), ('If I Fell', 'Love Me Do'))]

In [ ]:

beatles[beatles.song=='All You Need Is Love'].text

24695    Love, love, love, love, love, love, love, love, love.  \n  \nThere's nothing you can do that can't be done.  \nNothing you can sing that can't be sung.  \nNothing you can say, but you can learn  \nHow to play the game  \nIt's easy.  \nNothing you can make that can't be made.  \nNo one you can save that can't be saved.  \nNothing you can do, but you can learn  \nHow to be you in time  \nIt's easy.  \n  \nAll you need is love, all you need is love,  \nAll you need is love, love. Love is all you need.  \nLove, love, love, love, love, love, love, love, love.  \nAll you need is love, all you need is love,  \nAll you need is love, love. Love is all you need.  \n  \nThere's nothing you can know that isn't known.  \nNothing you can see that isn't shown.  \nThere's nowhere you can be that isn't where  \nYou're meant to be  \nIt's easy.  \n  \nAll you need is love, all you need is love,  \nAll you need is love, love. Love is all you need.  \nAll you need is love. (All together now).  \nAll you need is love. (Everybody).  \nAll you need is love, love. Love is all you need.  \nLove is all you need.  \nLove is all you need  \n  \n(Yesterday)  \n(Oh yeah)  \n(She love you, yeah, yeah, yeah)  \n(She love you, yeah, yeah, yeah)  \n(Oh, yesterday)\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Love Me Do'].text

24805    Love, love me do.  \nYou know I love you,  \nI'll always be true,  \nSo please, love me do.  \nWhoa, love me do.  \n  \nLove, love me do.  \nYou know I love you,  \nI'll always be true,  \nSo please, love me do.  \nWhoa, love me do.  \n  \nSomeone to love,  \nSomebody new.  \nSomeone to love,  \nSomeone like you.  \n  \nLove, love me do.  \nYou know I love you,  \nI'll always be true,  \nSo please, love me do.  \nWhoa, love me do.  \n  \nLove, love me do.  \nYou know I love you,  \nI'll always be true,  \nSo please, love me do.  \nWhoa, love me do.  \nYeah, love me do.  \nWhoa, oh, love me do.\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone'].text

24768    If I needed someone to love  \nYou're the one that I'd be thinking of  \nIf I needed someone  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone  \nAh, ah, ah, ah  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone  \nAh, ah\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone To Love'].text

24769    If I needed someone to love  \nYoure the woman I'd be thinking of  \nIf I needed someone  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \n  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \n  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone  \nIf I needed someone to love  \nYoure the woman I'd be thinking of  \nIf I needed someone  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \n  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone  \n  \nIf I had some more time to spend  \nThen I guess I'd be with you my friend  \nIf I needed someone  \n  \nHad you come some other day  \nThen it might not have been like this  \nBut you see now I'm too much in love  \n  \nCarve your number on my wall  \nAnd maybe you will get a call from me  \nIf I needed someone\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Have A Banana!'].text

1221    [Speech]  \n  \nBrian Matthew: Is that it? Is that the end?  \nPaul: Yeah, yeah, that's it.  \nJohn: Fade, fade!  \nBrian: Good track. Oh, well, we'll stop there, stop there, stop there.  \nJohn: What an end!  \nBrian: Quiet! All right, George.  \nJohn: Fade!  \nBrian: Hold it!  \nGeorge: Oh, thank you.  \nJohn: Fade, you silly.  \nBrian: Well, we did. We did that. Oh, no! No! We've done that bit!  \nJohn: The train comes in now.  \nBrian: We did that.  \nJohn: Yeah.  \nBrian: To pove we weren't playing the record, then, you see. 'Cause,\notherwise, there's no point in you being here, is there? Ha, ha, ha!  \nJohn: Yeah, we did that, 'cause it sounds just like it, don't it?  \nBrian: Pretty cool lot of fellows, aren't you? Here, Ringo, have a banana,\ncatch!\n\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Crinsk Dee Night'].text

24713    [Speech]  \n  \nBrian Matthew: The next few minutes, we're in the lap of the gods and the\nhands of the Beatles. In my young days, when I was a lad, they used to have\nactors in films and now that they--  \nPaul: Yes?  \nJohn: Hey! Listen!  \nPaul: It's all changed, now, Brian. They're not doing that, no actors.  \nJohn: It's all changed, now.  \nBrian: But this is what I wonder. In those days, the actors used to say their\nbest bits were left on the cutting room floor. Did you find that?  \nJohn: No, no, no, those were the good bits in the film. You should have seen\nthe rest.  \nBrian: Yes?  \nJohn: Rubbish!  \nBrian: Was it, really?  \nJohn: Even worse, yes.  \nBrian: Who was worst?  \nJohn: Oh, Paul.  \nBrian: I see.  \nPaul: I think John was about the worst.  \nJohn: No, it was you.  \nPaul: Oh, Ringo was very good. He was. He's a good lad.  \nBrian: He was. They're saying he's a new Charlie Chaplin. Do you think that's\nright?  \nJohn: He was miming.  \nPaul: You, too, with Jason.  \nJohn: Oh, yes, he's an old one. Okay, Ring?  \nBrian: Beginning to look like that. Now, then--  \nRingo: All right, John. Can you hear me?  \nPaul: Can you hear him? Hello!  \nBrian: Not really. I hope not. I hope not!  \nJohn: We brought you the flowers, Ring.  \nBrian: He's not allowed to talk.  \nRingo: Eh?  \nJohn: We brought you the flowers.  \nRingo: Oh, good.  \nJohn: And the grapes.  \nRingo: Oh, I like grapes.  \nPaul: He likes grapes.  \nGeorge: We've been to Portugal.  \nBrian: Guess who's, guess who's top of the pops in Portugal, then.  \nAll: Who?  \nBrian: Los Beatles.  \nJohn: Los Beatles? Great, great laugh.  \nBrian: I don't suppose you know the title of your film in Portuguese?  \nJohn: No. Crinsk dee Night?  \nBrian: Could be. Let's hear the number, shall we?  \nJohn: Right\n\n
Name: text, dtype: object

### Question: Compare the results. Which Vectorizer seems to do a better job?

> Based on the output, I can assume Count Vectorizer did better because it has more confidence that the songs it compared as almost the same. Even the title and its theme are almost similar. Therefore, I think Count Vectorizer did the best.

# Supplementary Activity

* Use a dataset that consists of text document
* Remove special characters
* Compare the similar document using Count Vector and TF-IDF Vectorizer
* Use the cosine similarity to measure the similarity of text

## Extracting the Data

In [ ]:

import chardet

with open(os.path.join(data_path, 'Corona_NLP.csv'), 'rb') as f:
    result = chardet.detect(f.read(10000))

print(result)

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

Since there is a 0.01% text that are not encoded by utf-8. I had to add encoding_errors='replace'

In [ ]:
#type your code here
data = pd.read_csv(os.path.join(data_path, 'Corona_NLP.csv'), encoding='UTF-8',
                   encoding_errors='replace')
data.head()

,UserName,ScreenName,Location,TweetAt,OriginalTweet,Sentiment
0,3799,48751,London,16-03-2020,@MeNyrbie @Phil_Gahan @Chrisitv https://t.co/iFz9FAn2Pa and https://t.co/xX6ghGFzCC and https://t.co/I2NlzdxNo8,Neutral
1,3800,48752,UK,16-03-2020,advice Talk to your neighbours family to exchange phone numbers create contact list with phone numbers of neighbours schools employer chemist GP set up online shopping accounts if poss adequate supplies of regular meds but not over order,Positive
2,3801,48753,Vagabonds,16-03-2020,"Coronavirus Australia: Woolworths to give elderly, disabled dedicated shopping hours amid COVID-19 outbreak https://t.co/bInCA9Vp8P",Positive
3,3802,48754,NaN,16-03-2020,"My food stock is not the only one which is empty...\r\r\n\r\r\nPLEASE, don't panic, THERE WILL BE ENOUGH FOOD FOR EVERYONE if you do not take more than you need. \r\r\nStay calm, stay safe.\r\r\n\r\r\n#COVID19france #COVID_19 #COVID19 #coronavirus #confinement #Confinementotal #ConfinementGeneral https://t.co/zrlG0Z520j",Positive
4,3803,48755,NaN,16-03-2020,"Me, ready to go at supermarket during the #COVID19 outbreak.\r\r\n\r\r\nNot because I'm paranoid, but because my food stock is litteraly empty. The #coronavirus is a serious thing, but please, don't panic. It causes shortage...\r\r\n\r\r\n#CoronavirusFrance #restezchezvous #StayAtHome #confinement https://t.co/usmuaLq72n",Extremely Negative

In [ ]:
data.shape

(41157, 6)

In [ ]:
data = data.sample(n=1000, random_state=1234)

## Transforming the Data

### **Discussion 5.1 | NLP Preprocessing**
* Tokenize (words)
* Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)
* Tokenize (words with remove punctuation and all lowercase)
* Tokenize (words with remove punctuation, all lowercase and  remove stop words)
* Tokenize (words with remove punctuation, all lowercase and  remove stop words, with speech_tagging)

In [ ]:
import nltk
import re
import string

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [ ]:
#@title Tokenize(words)
from nltk.tokenize import word_tokenize

tokens = data['OriginalTweet'].apply(word_tokenize)
print(tokens)

14188                                                                                                                                                                                                                                                                                [Anyone, else, keep, wondering, how, it, would, be, different, if, @, HillaryClinton, were, president, ?]
15722                                                                                                                                                                                                                                                   [Ran, out, of, toilet, paper, ., #, CoronavirusPandemic, #, COVID, ?, 19, #, toiletpaper, #, coronavirus, https, :, //t.co/ZXMzraLCo3]
29193                                                                                                                                                                                             [This, isnt, just, #, M, &, amp, ;, S, food, ,, This, is, every, bluddy, #, supermarket, you, go, to, lack, of, #, shoppers, to, buy, food, !, !, #, coronavirus, #, Corvid_19, #, lockdown]
1270                                                                                                                                     [Just, went, to, the, grocery, store, for, essentials, (, carbohydrates, ), and, it, was, a, little, weird, ., None, of, the, usual, milling, just, people, getting, their, stuff, and, GTFO, ., #, COVID2019, #, grocerystores, #, SocialDistancing]
10071                                                                                                                                                        [Inventory, planning, is, the, name, of, the, game, right, now, in, packaged, staples, as, brands, dealing, with, sudden, surges, in, demand, owing, to, 19, try, to, predict, how, long, current, buying, patterns, might, last]
                                                                                                                                                                                                 ...
13052                                                              [Was, just, at, the, grocery, store, and, a, man, in, another, aisle, was, short, of, money, and, could, n't, complete, his, purchase, of, basic, staples, ., He, said, ,, ``, I, 'll, just, have, to, put, some, things, back, ., '', Within, a, few, seconds, several, step, up, to, pay, for, the, rest, ., #, Covid_19]
13739                              [Amount, of, time, Id, have, to, wait, in, line, OUTSIDE, each, supermarket, close, to, my, house, if, I, wanted, to, go, buy, groceries, now, ., This, is, downtown, Milan, ., Online, delivery, has, become, virtually, unavailable, ., Shits, getting, real, ., #, CoronaVirusitaly, #, Covid_19, #, CoronavirusPandemic, https, :, //t.co/vSGZ71DuA0]
11810                                                                                                                                                                                                                                        [Me, to, all, the, South, Asian, establishments, quadrupling, their, prices, for, essential, items, #, CoronaCrisis, https, :, //t.co/bXQEogwxg2]
39692    [This, is, Dusty, Gearhard, ., He, is, a, grocery, store, worker, at, Homeland, Stores, in, Oklahoma, ., He, says, he, sees, families, coming, to, the, store, ., He, says, shoppers, arent, social, distancing, and, most, dont, wear, masks, ., And, until, this, changes, -, his, life, is, at, stake, ..., #, Covid_19, #, GroceryWorkers, @, wjz, https, :, //t.co/qzZ2uY425c]
36939                                                                                                                                                                                  [Do, you, really, need, that, toilet, paper, ?, #, It, #, everythingfloats, #, toiletpaper, #, tp, #, coronavirus, #, covid19, #, nypause, #, stephenking, @, StephenKing, https, :, //t.co/R2TuXNGQe8]
Name: OriginalTweet, Length: 1000, dtype: object

In [ ]:
#@title Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)

clean_tokens = [word for sentence in tokens for word in sentence
                if word.isalpha()]
clean_tokens

['Anyone',
 'else',
 'keep',
 'wondering',
 'how',
 'it',
 'would',
 'be',
 'different',
 'if',
 'HillaryClinton',
 'were',
 'president',
 'Ran',
 'out',
 'of',
 'toilet',
 'paper',
 'CoronavirusPandemic',
 'COVID',
 'toiletpaper',
 'coronavirus',
 'https',
 'This',
 'isnt',
 'just',
 'M',
 'amp',
 'S',
 'food',
 'This',
 'is',
 'every',
 'bluddy',
 'supermarket',
 'you',
 'go',
 'to',
 'lack',
 'of',
 'shoppers',
 'to',
 'buy',
 'food',
 'coronavirus',
 'lockdown',
 'Just',
 'went',
 'to',
 'the',
 'grocery',
 'store',
 'for',
 'essentials',
 'carbohydrates',
 'and',
 'it',
 'was',
 'a',
 'little',
 'weird',
 'None',
 'of',
 'the',
 'usual',
 'milling',
 'just',
 'people',
 'getting',
 'their',
 'stuff',
 'and',
 'GTFO',
 'grocerystores',
 'SocialDistancing',
 'Inventory',
 'planning',
 'is',
 'the',
 'name',
 'of',
 'the',
 'game',
 'right',
 'now',
 'in',
 'packaged',
 'staples',
 'as',
 'brands',
 'dealing',
 'with',
 'sudden',
 'surges',
 'in',
 'demand',
 'owing',
 'to',
 'try',
 'to',
 'predict',
 'how',
 'long',
 'current',
 'buying',
 'patterns',
 'might',
 'last',
 'Isolation',
 'how',
 'on',
 'earth',
 'will',
 'you',
 'ask',
 'us',
 'to',
 'stay',
 'at',
 'home',
 'no',
 'work',
 'no',
 'food',
 'no',
 'money',
 'to',
 'stock',
 'the',
 'house',
 'naija',
 'hmmmmm',
 'if',
 'no',
 'body',
 'is',
 'crying',
 'out',
 'pls',
 'and',
 'pls',
 'o',
 'hear',
 'my',
 'cry',
 'o',
 'i',
 'need',
 'money',
 'so',
 'the',
 'isolation',
 'thing',
 'can',
 'work',
 'o',
 'make',
 'i',
 'come',
 'isolate',
 'die',
 'of',
 'hunger',
 'donjazzy',
 'iruntow',
 'Went',
 'to',
 'grocery',
 'off',
 'for',
 'elderly',
 'before',
 'I',
 'headed',
 'back',
 'home',
 'I',
 'REMOVED',
 'outside',
 'then',
 'hit',
 'Grocery',
 'store',
 'controlled',
 'line',
 'by',
 'havin',
 'only',
 'a',
 'handful',
 'of',
 'avail',
 'N',
 'until',
 'turn',
 'to',
 'shop',
 'it',
 'helped',
 'with',
 'Soc',
 'The',
 'impact',
 'of',
 'coronavirus',
 'on',
 'Singapore',
 'Private',
 'Home',
 'Prices',
 'Down',
 'In',
 'https',
 'believe',
 'just',
 'gone',
 'to',
 'order',
 'my',
 'tesco',
 'online',
 'shopping',
 'and',
 'there',
 'a',
 'single',
 'pack',
 'of',
 'fresh',
 'chicken',
 'Along',
 'with',
 'pasta',
 'toilet',
 'roll',
 'hand',
 'soap',
 'and',
 'more',
 'believe',
 'how',
 'Coronavirus',
 'has',
 'shown',
 'such',
 'an',
 'grotesque',
 'side',
 'of',
 'society',
 'Greedy',
 'selfish',
 'bastards',
 'coronavirusuk',
 'This',
 'past',
 'week',
 'stories',
 'from',
 'all',
 'over',
 'America',
 'show',
 'farmers',
 'dumping',
 'milk',
 'plowing',
 'under',
 'crops',
 'because',
 'normal',
 'demand',
 'shifts',
 'Look',
 'we',
 'have',
 'hungry',
 'Americans',
 'without',
 'incomes',
 'Fed',
 'Govt',
 'IS',
 'FAILING',
 'AGAIN',
 'If',
 'Americans',
 'survive',
 'we',
 'must',
 'face',
 'food',
 'shortages',
 'next',
 'KellyO',
 'NYGovCuomo',
 'In',
 'Canada',
 'the',
 'Competition',
 'Bureau',
 'is',
 'prepared',
 'to',
 'pursue',
 'any',
 'cases',
 'of',
 'price',
 'gouging',
 'https',
 'By',
 'declaring',
 'a',
 'state',
 'of',
 'emergency',
 'Ontario',
 'has',
 'the',
 'power',
 'to',
 'freeze',
 'prices',
 'Fuel',
 'for',
 'Thought',
 'CrudeOil',
 'prices',
 'have',
 'corrected',
 'by',
 'almost',
 'since',
 'Dec',
 'as',
 'a',
 'result',
 'of',
 'the',
 'crisis',
 'As',
 'one',
 'of',
 'the',
 'largest',
 'oil',
 'importers',
 'in',
 'the',
 'world',
 'India',
 'imports',
 'around',
 'of',
 'its',
 'oil',
 'demand',
 'CoronaNews',
 'Hungarian',
 'oil',
 'and',
 'gas',
 'company',
 'MOL',
 'has',
 'switched',
 'over',
 'a',
 'production',
 'line',
 'to',
 'sanitizers',
 'made',
 'earlier',
 'windshield',
 'cleaner',
 'fluid',
 'Hungary',
 'MOL',
 'sanitizer',
 'coronavirus',
 'Read',
 'more',
 'https',
 'Picture',
 'https',
 'We',
 'have',
 'recently',
 'seen',
 'an',
 'increase',
 'in',
 'people',
 'shopping',
 'online',
 'In',
 'the',
 'short',
 'term',
 'this',
 'is',
 'having',
 'an',
 'impact',
 'on',
 'how',
 'we',
 'serve',
 'our',
 'customers',
 'You',
 'will',
 'notice',
 'that',
 'we',
 'are',
 'currently',
 'out',
 'of',
 'stock',
 'on',
 'some',
 'brands',
 'amp',
 'items',
 'in',
 'household',
 'staples',
 'categories',
 'https',
 'For',
 'those',
 'who',
 'are',
 'in',
 'panic',
 'mode',
 'yet',
 'when',
 'would',
 'you',
 'suggest',
 'No',
 'food',
 'Tanks',
 'in',
 'the',
 'street',
 'Right',
 'now',
 'I',
 'do',
 'even',
 'know',
 'anymore',
 'or',
 'who',
 'to',
 'trust',
 'coronavirus',
 'Good',
 'evening',
 'lovelies',
 'hope',
 'well',
 'my',
 'day',
 'has',
 'been',
 'dull',
 'I',
 'did',
 'some',
 'online',
 'shopping',
 'from',
 'AmazonUK',
 'and',
 'chilled',
 'Xx',
 'TheArchers',
 'coronavirus',
 'Has',
 'anyone',
 'experienced',
 'getting',
 'headaches',
 'even',
 'if',
 'slight',
 'from',
 'shopping',
 'in',
 'a',
 'grocery',
 'store',
 'which',
 'was',
 'full',
 'of',
 'shoppers',
 'not',
 'SocialDistancing',
 'A',
 'theory',
 'suggests',
 'buildings',
 'are',
 'properly',
 'ventilated',
 'to',
 'allow',
 'the',
 'contaminated',
 'air',
 'from',
 'the',
 'breath',
 'of',
 'shoppers',
 'to',
 'dissipate',
 'Day',
 'still',
 'have',
 'needed',
 'to',
 'go',
 'to',
 'a',
 'supermarket',
 'Am',
 'I',
 'doing',
 'this',
 'wrong',
 'coronavirus',
 'cdnpoli',
 'uspoli',
 'coronavirus',
 'CoronavirusPandemic',
 'Vicki',
 'today',
 'my',
 'supermarket',
 'had',
 'toilet',
 'paper',
 'wrapped',
 'in',
 'totally',
 'clear',
 'plastic',
 'no',
 'printing',
 'whatsoever',
 'I',
 'figure',
 'the',
 'paper',
 'was',
 'made',
 'crushed',
 'sandpap',
 'If',
 'you',
 'live',
 'in',
 'area',
 'work',
 'in',
 'the',
 'and',
 'can',
 't',
 'get',
 'to',
 'the',
 'supermarket',
 'then',
 'DM',
 'me',
 'and',
 'let',
 'me',
 'know',
 'what',
 'you',
 'need',
 'and',
 'we',
 'll',
 'deliver',
 'it',
 'when',
 'you',
 're',
 'home',
 'from',
 'your',
 'shift',
 'fighting',
 'I',
 'ashamed',
 'to',
 'be',
 'a',
 'part',
 'of',
 'this',
 'city',
 'right',
 'now',
 'Not',
 'seeing',
 'much',
 'evidence',
 'of',
 'together',
 'coronavirus',
 'StopHoarding',
 'panicbuyinguk',
 'London',
 'As',
 'part',
 'of',
 'the',
 'consumer',
 'coronavirus',
 'response',
 'we',
 'also',
 'saw',
 'early',
 'hoarding',
 'of',
 'important',
 'hygeinic',
 'and',
 'medical',
 'supplies',
 'like',
 'hand',
 'sanitizer',
 'sterilizing',
 'wipes',
 'and',
 'most',
 'importantly',
 'surgical',
 'masks',
 'We',
 'should',
 'note',
 'that',
 'these',
 'hoarding',
 'behaviors',
 'were',
 'global',
 'All',
 'Hot',
 'Topic',
 'stores',
 'will',
 'be',
 'closed',
 'for',
 'a',
 'period',
 'of',
 'time',
 'due',
 'to',
 'health',
 'concerns',
 'During',
 'this',
 'time',
 'all',
 'store',
 'employees',
 'will',
 'be',
 'paid',
 'https',
 'Shops',
 'markets',
 'shopping',
 'malls',
 'and',
 'restaurants',
 'remain',
 'closed',
 'in',
 'different',
 'cities',
 'of',
 'Pakistan',
 'as',
 'the',
 'country',
 'has',
 'imposed',
 'a',
 'ban',
 'on',
 'movement',
 'to',
 'stop',
 'the',
 'spread',
 'of',
 'The',
 'following',
 'pictures',
 'show',
 'the',
 'empty',
 'roads',
 'in',
 'Karachi',
 'Islamabad',
 'and',
 'Bannu',
 'Photos',
 'Online',
 'Called',
 'in',
 'supermarket',
 'on',
 'way',
 'home',
 'We',
 'are',
 'a',
 'generation',
 'who',
 'are',
 'used',
 'to',
 'having',
 'plenty',
 'instantaneously',
 'Now',
 'is',
 'the',
 'time',
 'to',
 'think',
 'about',
 'others',
 'and',
 'adjust',
 'our',
 'behaviours',
 'lookoutforothers',
 'Coronavirus',
 'UK',
 'Consumer',
 'diary',
 'studies',
 'coronavirus',
 'https',
 'via',
 'SlideShare',
 'Went',
 'to',
 'the',
 'supermarket',
 'to',
 'get',
 'some',
 'food',
 'and',
 'a',
 'lady',
 'pushed',
 'me',
 'to',
 'get',
 'to',
 'some',
 'toilet',
 'paper',
 'coronavirus',
 'making',
 'people',
 'crazy',
 'I',
 'ask',
 'myself',
 'what',
 'is',
 'Sprint',
 'doing',
 'for',
 'customers',
 'during',
 'coronavirus',
 'layoffs',
 'nounemployment',
 'period',
 'easy',
 'answer',
 'I',
 'got',
 'a',
 'text',
 'today',
 'my',
 'services',
 'are',
 'getting',
 'shut',
 'off',
 'if',
 'I',
 'make',
 'a',
 'payment',
 'stock',
 'up',
 'on',
 'food',
 'and',
 'household',
 'necessities',
 'for',
 'upcoming',
 'quarantine',
 'or',
 'pay',
 'sprint',
 'Will',
 'the',
 'crisis',
 'drive',
 'down',
 'SF',
 'rent',
 'prices',
 'https',
 'https',
 'FREE',
 'FOOD',
 'Event',
 'is',
 'over',
 'today',
 'Back',
 'by',
 'popular',
 'demand',
 'on',
 'Thursday',
 'from',
 'till',
 'noon',
 'Check',
 'out',
 'previous',
 'tweets',
 'for',
 'link',
 'to',
 'locations',
 'or',
 'visit',
 'our',
 'website',
 'for',
 'more',
 'information',
 'no',
 'reason',
 'this',
 'country',
 'should',
 'be',
 'in',
 'shortage',
 'of',
 'PPE',
 'hand',
 'sanitizer',
 'toilet',
 'paper',
 'anything',
 'really',
 'Coronavirus',
 'Man',
 'arrested',
 'after',
 'punching',
 'mother',
 'over',
 'toilet',
 'tissue',
 'paper',
 'Link',
 'in',
 'my',
 'bio',
 'linkinbio',
 'news',
 'fight',
 'toiletpaper',
 'coronavirus',
 'qurantine',
 'realitytv',
 'gossip',
 'police',
 'arrested',
 'handsanitizer',
 'https',
 'ssupnow',
 'Sanitizer',
 'Italy',
 'Wuhan',
 'Grocery',
 'coronavirus',
 'contest',
 'alert',
 'GiveawayAlert',
 'competition',
 'puzzles',
 'ssupnow',
 'Join',
 'guys',
 'Drrashiaggarwal',
 'sapnaarathor',
 'Tu',
 'video',
 'site',
 'trends',
 'ways',
 'consumers',
 'are',
 'turning',
 'to',
 'YouTube',
 'to',
 'help',
 'cope',
 'with',
 'social',
 'isolation',
 'what',
 'could',
 'this',
 'mean',
 'for',
 'your',
 'business',
 'From',
 'ThinkwithGoogle',
 'https',
 'Video',
 'Consumer',
 'Behaviour',
 'socialisolation',
 'https',
 'In',
 'just',
 'a',
 'week',
 'at',
 'home',
 'on',
 'lockdown',
 'used',
 'to',
 'raise',
 'for',
 'response',
 'by',
 'collecting',
 'toilet',
 'paper',
 'hand',
 'sanitizer',
 'and',
 'face',
 'masks',
 'and',
 'you',
 'can',
 'too',
 'by',
 'visiting',
 'and',
 'downloading',
 'the',
 'beta',
 'app',
 'Update',
 'For',
 ...]

In [ ]:
#@title Tokenize (words with remove punctuation and all lowercase)
clean_tokens = [word.lower() for word in clean_tokens if word.isalpha()]
clean_tokens

['anyone',
 'else',
 'keep',
 'wondering',
 'how',
 'it',
 'would',
 'be',
 'different',
 'if',
 'hillaryclinton',
 'were',
 'president',
 'ran',
 'out',
 'of',
 'toilet',
 'paper',
 'coronaviruspandemic',
 'covid',
 'toiletpaper',
 'coronavirus',
 'https',
 'this',
 'isnt',
 'just',
 'm',
 'amp',
 's',
 'food',
 'this',
 'is',
 'every',
 'bluddy',
 'supermarket',
 'you',
 'go',
 'to',
 'lack',
 'of',
 'shoppers',
 'to',
 'buy',
 'food',
 'coronavirus',
 'lockdown',
 'just',
 'went',
 'to',
 'the',
 'grocery',
 'store',
 'for',
 'essentials',
 'carbohydrates',
 'and',
 'it',
 'was',
 'a',
 'little',
 'weird',
 'none',
 'of',
 'the',
 'usual',
 'milling',
 'just',
 'people',
 'getting',
 'their',
 'stuff',
 'and',
 'gtfo',
 'grocerystores',
 'socialdistancing',
 'inventory',
 'planning',
 'is',
 'the',
 'name',
 'of',
 'the',
 'game',
 'right',
 'now',
 'in',
 'packaged',
 'staples',
 'as',
 'brands',
 'dealing',
 'with',
 'sudden',
 'surges',
 'in',
 'demand',
 'owing',
 'to',
 'try',
 'to',
 'predict',
 'how',
 'long',
 'current',
 'buying',
 'patterns',
 'might',
 'last',
 'isolation',
 'how',
 'on',
 'earth',
 'will',
 'you',
 'ask',
 'us',
 'to',
 'stay',
 'at',
 'home',
 'no',
 'work',
 'no',
 'food',
 'no',
 'money',
 'to',
 'stock',
 'the',
 'house',
 'naija',
 'hmmmmm',
 'if',
 'no',
 'body',
 'is',
 'crying',
 'out',
 'pls',
 'and',
 'pls',
 'o',
 'hear',
 'my',
 'cry',
 'o',
 'i',
 'need',
 'money',
 'so',
 'the',
 'isolation',
 'thing',
 'can',
 'work',
 'o',
 'make',
 'i',
 'come',
 'isolate',
 'die',
 'of',
 'hunger',
 'donjazzy',
 'iruntow',
 'went',
 'to',
 'grocery',
 'off',
 'for',
 'elderly',
 'before',
 'i',
 'headed',
 'back',
 'home',
 'i',
 'removed',
 'outside',
 'then',
 'hit',
 'grocery',
 'store',
 'controlled',
 'line',
 'by',
 'havin',
 'only',
 'a',
 'handful',
 'of',
 'avail',
 'n',
 'until',
 'turn',
 'to',
 'shop',
 'it',
 'helped',
 'with',
 'soc',
 'the',
 'impact',
 'of',
 'coronavirus',
 'on',
 'singapore',
 'private',
 'home',
 'prices',
 'down',
 'in',
 'https',
 'believe',
 'just',
 'gone',
 'to',
 'order',
 'my',
 'tesco',
 'online',
 'shopping',
 'and',
 'there',
 'a',
 'single',
 'pack',
 'of',
 'fresh',
 'chicken',
 'along',
 'with',
 'pasta',
 'toilet',
 'roll',
 'hand',
 'soap',
 'and',
 'more',
 'believe',
 'how',
 'coronavirus',
 'has',
 'shown',
 'such',
 'an',
 'grotesque',
 'side',
 'of',
 'society',
 'greedy',
 'selfish',
 'bastards',
 'coronavirusuk',
 'this',
 'past',
 'week',
 'stories',
 'from',
 'all',
 'over',
 'america',
 'show',
 'farmers',
 'dumping',
 'milk',
 'plowing',
 'under',
 'crops',
 'because',
 'normal',
 'demand',
 'shifts',
 'look',
 'we',
 'have',
 'hungry',
 'americans',
 'without',
 'incomes',
 'fed',
 'govt',
 'is',
 'failing',
 'again',
 'if',
 'americans',
 'survive',
 'we',
 'must',
 'face',
 'food',
 'shortages',
 'next',
 'kellyo',
 'nygovcuomo',
 'in',
 'canada',
 'the',
 'competition',
 'bureau',
 'is',
 'prepared',
 'to',
 'pursue',
 'any',
 'cases',
 'of',
 'price',
 'gouging',
 'https',
 'by',
 'declaring',
 'a',
 'state',
 'of',
 'emergency',
 'ontario',
 'has',
 'the',
 'power',
 'to',
 'freeze',
 'prices',
 'fuel',
 'for',
 'thought',
 'crudeoil',
 'prices',
 'have',
 'corrected',
 'by',
 'almost',
 'since',
 'dec',
 'as',
 'a',
 'result',
 'of',
 'the',
 'crisis',
 'as',
 'one',
 'of',
 'the',
 'largest',
 'oil',
 'importers',
 'in',
 'the',
 'world',
 'india',
 'imports',
 'around',
 'of',
 'its',
 'oil',
 'demand',
 'coronanews',
 'hungarian',
 'oil',
 'and',
 'gas',
 'company',
 'mol',
 'has',
 'switched',
 'over',
 'a',
 'production',
 'line',
 'to',
 'sanitizers',
 'made',
 'earlier',
 'windshield',
 'cleaner',
 'fluid',
 'hungary',
 'mol',
 'sanitizer',
 'coronavirus',
 'read',
 'more',
 'https',
 'picture',
 'https',
 'we',
 'have',
 'recently',
 'seen',
 'an',
 'increase',
 'in',
 'people',
 'shopping',
 'online',
 'in',
 'the',
 'short',
 'term',
 'this',
 'is',
 'having',
 'an',
 'impact',
 'on',
 'how',
 'we',
 'serve',
 'our',
 'customers',
 'you',
 'will',
 'notice',
 'that',
 'we',
 'are',
 'currently',
 'out',
 'of',
 'stock',
 'on',
 'some',
 'brands',
 'amp',
 'items',
 'in',
 'household',
 'staples',
 'categories',
 'https',
 'for',
 'those',
 'who',
 'are',
 'in',
 'panic',
 'mode',
 'yet',
 'when',
 'would',
 'you',
 'suggest',
 'no',
 'food',
 'tanks',
 'in',
 'the',
 'street',
 'right',
 'now',
 'i',
 'do',
 'even',
 'know',
 'anymore',
 'or',
 'who',
 'to',
 'trust',
 'coronavirus',
 'good',
 'evening',
 'lovelies',
 'hope',
 'well',
 'my',
 'day',
 'has',
 'been',
 'dull',
 'i',
 'did',
 'some',
 'online',
 'shopping',
 'from',
 'amazonuk',
 'and',
 'chilled',
 'xx',
 'thearchers',
 'coronavirus',
 'has',
 'anyone',
 'experienced',
 'getting',
 'headaches',
 'even',
 'if',
 'slight',
 'from',
 'shopping',
 'in',
 'a',
 'grocery',
 'store',
 'which',
 'was',
 'full',
 'of',
 'shoppers',
 'not',
 'socialdistancing',
 'a',
 'theory',
 'suggests',
 'buildings',
 'are',
 'properly',
 'ventilated',
 'to',
 'allow',
 'the',
 'contaminated',
 'air',
 'from',
 'the',
 'breath',
 'of',
 'shoppers',
 'to',
 'dissipate',
 'day',
 'still',
 'have',
 'needed',
 'to',
 'go',
 'to',
 'a',
 'supermarket',
 'am',
 'i',
 'doing',
 'this',
 'wrong',
 'coronavirus',
 'cdnpoli',
 'uspoli',
 'coronavirus',
 'coronaviruspandemic',
 'vicki',
 'today',
 'my',
 'supermarket',
 'had',
 'toilet',
 'paper',
 'wrapped',
 'in',
 'totally',
 'clear',
 'plastic',
 'no',
 'printing',
 'whatsoever',
 'i',
 'figure',
 'the',
 'paper',
 'was',
 'made',
 'crushed',
 'sandpap',
 'if',
 'you',
 'live',
 'in',
 'area',
 'work',
 'in',
 'the',
 'and',
 'can',
 't',
 'get',
 'to',
 'the',
 'supermarket',
 'then',
 'dm',
 'me',
 'and',
 'let',
 'me',
 'know',
 'what',
 'you',
 'need',
 'and',
 'we',
 'll',
 'deliver',
 'it',
 'when',
 'you',
 're',
 'home',
 'from',
 'your',
 'shift',
 'fighting',
 'i',
 'ashamed',
 'to',
 'be',
 'a',
 'part',
 'of',
 'this',
 'city',
 'right',
 'now',
 'not',
 'seeing',
 'much',
 'evidence',
 'of',
 'together',
 'coronavirus',
 'stophoarding',
 'panicbuyinguk',
 'london',
 'as',
 'part',
 'of',
 'the',
 'consumer',
 'coronavirus',
 'response',
 'we',
 'also',
 'saw',
 'early',
 'hoarding',
 'of',
 'important',
 'hygeinic',
 'and',
 'medical',
 'supplies',
 'like',
 'hand',
 'sanitizer',
 'sterilizing',
 'wipes',
 'and',
 'most',
 'importantly',
 'surgical',
 'masks',
 'we',
 'should',
 'note',
 'that',
 'these',
 'hoarding',
 'behaviors',
 'were',
 'global',
 'all',
 'hot',
 'topic',
 'stores',
 'will',
 'be',
 'closed',
 'for',
 'a',
 'period',
 'of',
 'time',
 'due',
 'to',
 'health',
 'concerns',
 'during',
 'this',
 'time',
 'all',
 'store',
 'employees',
 'will',
 'be',
 'paid',
 'https',
 'shops',
 'markets',
 'shopping',
 'malls',
 'and',
 'restaurants',
 'remain',
 'closed',
 'in',
 'different',
 'cities',
 'of',
 'pakistan',
 'as',
 'the',
 'country',
 'has',
 'imposed',
 'a',
 'ban',
 'on',
 'movement',
 'to',
 'stop',
 'the',
 'spread',
 'of',
 'the',
 'following',
 'pictures',
 'show',
 'the',
 'empty',
 'roads',
 'in',
 'karachi',
 'islamabad',
 'and',
 'bannu',
 'photos',
 'online',
 'called',
 'in',
 'supermarket',
 'on',
 'way',
 'home',
 'we',
 'are',
 'a',
 'generation',
 'who',
 'are',
 'used',
 'to',
 'having',
 'plenty',
 'instantaneously',
 'now',
 'is',
 'the',
 'time',
 'to',
 'think',
 'about',
 'others',
 'and',
 'adjust',
 'our',
 'behaviours',
 'lookoutforothers',
 'coronavirus',
 'uk',
 'consumer',
 'diary',
 'studies',
 'coronavirus',
 'https',
 'via',
 'slideshare',
 'went',
 'to',
 'the',
 'supermarket',
 'to',
 'get',
 'some',
 'food',
 'and',
 'a',
 'lady',
 'pushed',
 'me',
 'to',
 'get',
 'to',
 'some',
 'toilet',
 'paper',
 'coronavirus',
 'making',
 'people',
 'crazy',
 'i',
 'ask',
 'myself',
 'what',
 'is',
 'sprint',
 'doing',
 'for',
 'customers',
 'during',
 'coronavirus',
 'layoffs',
 'nounemployment',
 'period',
 'easy',
 'answer',
 'i',
 'got',
 'a',
 'text',
 'today',
 'my',
 'services',
 'are',
 'getting',
 'shut',
 'off',
 'if',
 'i',
 'make',
 'a',
 'payment',
 'stock',
 'up',
 'on',
 'food',
 'and',
 'household',
 'necessities',
 'for',
 'upcoming',
 'quarantine',
 'or',
 'pay',
 'sprint',
 'will',
 'the',
 'crisis',
 'drive',
 'down',
 'sf',
 'rent',
 'prices',
 'https',
 'https',
 'free',
 'food',
 'event',
 'is',
 'over',
 'today',
 'back',
 'by',
 'popular',
 'demand',
 'on',
 'thursday',
 'from',
 'till',
 'noon',
 'check',
 'out',
 'previous',
 'tweets',
 'for',
 'link',
 'to',
 'locations',
 'or',
 'visit',
 'our',
 'website',
 'for',
 'more',
 'information',
 'no',
 'reason',
 'this',
 'country',
 'should',
 'be',
 'in',
 'shortage',
 'of',
 'ppe',
 'hand',
 'sanitizer',
 'toilet',
 'paper',
 'anything',
 'really',
 'coronavirus',
 'man',
 'arrested',
 'after',
 'punching',
 'mother',
 'over',
 'toilet',
 'tissue',
 'paper',
 'link',
 'in',
 'my',
 'bio',
 'linkinbio',
 'news',
 'fight',
 'toiletpaper',
 'coronavirus',
 'qurantine',
 'realitytv',
 'gossip',
 'police',
 'arrested',
 'handsanitizer',
 'https',
 'ssupnow',
 'sanitizer',
 'italy',
 'wuhan',
 'grocery',
 'coronavirus',
 'contest',
 'alert',
 'giveawayalert',
 'competition',
 'puzzles',
 'ssupnow',
 'join',
 'guys',
 'drrashiaggarwal',
 'sapnaarathor',
 'tu',
 'video',
 'site',
 'trends',
 'ways',
 'consumers',
 'are',
 'turning',
 'to',
 'youtube',
 'to',
 'help',
 'cope',
 'with',
 'social',
 'isolation',
 'what',
 'could',
 'this',
 'mean',
 'for',
 'your',
 'business',
 'from',
 'thinkwithgoogle',
 'https',
 'video',
 'consumer',
 'behaviour',
 'socialisolation',
 'https',
 'in',
 'just',
 'a',
 'week',
 'at',
 'home',
 'on',
 'lockdown',
 'used',
 'to',
 'raise',
 'for',
 'response',
 'by',
 'collecting',
 'toilet',
 'paper',
 'hand',
 'sanitizer',
 'and',
 'face',
 'masks',
 'and',
 'you',
 'can',
 'too',
 'by',
 'visiting',
 'and',
 'downloading',
 'the',
 'beta',
 'app',
 'update',
 'for',
 ...]

In [ ]:
#@title Tokenize (words with remove punctuation, all lowercase and remove stop words)
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

clean_tokens = [
    word.lower()
    for word in clean_tokens
    if word.isalpha() and word.lower() not in stop_words
]

clean_tokens

['anyone',
 'else',
 'keep',
 'wondering',
 'would',
 'different',
 'hillaryclinton',
 'president',
 'ran',
 'toilet',
 'paper',
 'coronaviruspandemic',
 'covid',
 'toiletpaper',
 'coronavirus',
 'https',
 'isnt',
 'amp',
 'food',
 'every',
 'bluddy',
 'supermarket',
 'go',
 'lack',
 'shoppers',
 'buy',
 'food',
 'coronavirus',
 'lockdown',
 'went',
 'grocery',
 'store',
 'essentials',
 'carbohydrates',
 'little',
 'weird',
 'none',
 'usual',
 'milling',
 'people',
 'getting',
 'stuff',
 'gtfo',
 'grocerystores',
 'socialdistancing',
 'inventory',
 'planning',
 'name',
 'game',
 'right',
 'packaged',
 'staples',
 'brands',
 'dealing',
 'sudden',
 'surges',
 'demand',
 'owing',
 'try',
 'predict',
 'long',
 'current',
 'buying',
 'patterns',
 'might',
 'last',
 'isolation',
 'earth',
 'ask',
 'us',
 'stay',
 'home',
 'work',
 'food',
 'money',
 'stock',
 'house',
 'naija',
 'hmmmmm',
 'body',
 'crying',
 'pls',
 'pls',
 'hear',
 'cry',
 'need',
 'money',
 'isolation',
 'thing',
 'work',
 'make',
 'come',
 'isolate',
 'die',
 'hunger',
 'donjazzy',
 'iruntow',
 'went',
 'grocery',
 'elderly',
 'headed',
 'back',
 'home',
 'removed',
 'outside',
 'hit',
 'grocery',
 'store',
 'controlled',
 'line',
 'havin',
 'handful',
 'avail',
 'n',
 'turn',
 'shop',
 'helped',
 'soc',
 'impact',
 'coronavirus',
 'singapore',
 'private',
 'home',
 'prices',
 'https',
 'believe',
 'gone',
 'order',
 'tesco',
 'online',
 'shopping',
 'single',
 'pack',
 'fresh',
 'chicken',
 'along',
 'pasta',
 'toilet',
 'roll',
 'hand',
 'soap',
 'believe',
 'coronavirus',
 'shown',
 'grotesque',
 'side',
 'society',
 'greedy',
 'selfish',
 'bastards',
 'coronavirusuk',
 'past',
 'week',
 'stories',
 'america',
 'show',
 'farmers',
 'dumping',
 'milk',
 'plowing',
 'crops',
 'normal',
 'demand',
 'shifts',
 'look',
 'hungry',
 'americans',
 'without',
 'incomes',
 'fed',
 'govt',
 'failing',
 'americans',
 'survive',
 'must',
 'face',
 'food',
 'shortages',
 'next',
 'kellyo',
 'nygovcuomo',
 'canada',
 'competition',
 'bureau',
 'prepared',
 'pursue',
 'cases',
 'price',
 'gouging',
 'https',
 'declaring',
 'state',
 'emergency',
 'ontario',
 'power',
 'freeze',
 'prices',
 'fuel',
 'thought',
 'crudeoil',
 'prices',
 'corrected',
 'almost',
 'since',
 'dec',
 'result',
 'crisis',
 'one',
 'largest',
 'oil',
 'importers',
 'world',
 'india',
 'imports',
 'around',
 'oil',
 'demand',
 'coronanews',
 'hungarian',
 'oil',
 'gas',
 'company',
 'mol',
 'switched',
 'production',
 'line',
 'sanitizers',
 'made',
 'earlier',
 'windshield',
 'cleaner',
 'fluid',
 'hungary',
 'mol',
 'sanitizer',
 'coronavirus',
 'read',
 'https',
 'picture',
 'https',
 'recently',
 'seen',
 'increase',
 'people',
 'shopping',
 'online',
 'short',
 'term',
 'impact',
 'serve',
 'customers',
 'notice',
 'currently',
 'stock',
 'brands',
 'amp',
 'items',
 'household',
 'staples',
 'categories',
 'https',
 'panic',
 'mode',
 'yet',
 'would',
 'suggest',
 'food',
 'tanks',
 'street',
 'right',
 'even',
 'know',
 'anymore',
 'trust',
 'coronavirus',
 'good',
 'evening',
 'lovelies',
 'hope',
 'well',
 'day',
 'dull',
 'online',
 'shopping',
 'amazonuk',
 'chilled',
 'xx',
 'thearchers',
 'coronavirus',
 'anyone',
 'experienced',
 'getting',
 'headaches',
 'even',
 'slight',
 'shopping',
 'grocery',
 'store',
 'full',
 'shoppers',
 'socialdistancing',
 'theory',
 'suggests',
 'buildings',
 'properly',
 'ventilated',
 'allow',
 'contaminated',
 'air',
 'breath',
 'shoppers',
 'dissipate',
 'day',
 'still',
 'needed',
 'go',
 'supermarket',
 'wrong',
 'coronavirus',
 'cdnpoli',
 'uspoli',
 'coronavirus',
 'coronaviruspandemic',
 'vicki',
 'today',
 'supermarket',
 'toilet',
 'paper',
 'wrapped',
 'totally',
 'clear',
 'plastic',
 'printing',
 'whatsoever',
 'figure',
 'paper',
 'made',
 'crushed',
 'sandpap',
 'live',
 'area',
 'work',
 'get',
 'supermarket',
 'dm',
 'let',
 'know',
 'need',
 'deliver',
 'home',
 'shift',
 'fighting',
 'ashamed',
 'part',
 'city',
 'right',
 'seeing',
 'much',
 'evidence',
 'together',
 'coronavirus',
 'stophoarding',
 'panicbuyinguk',
 'london',
 'part',
 'consumer',
 'coronavirus',
 'response',
 'also',
 'saw',
 'early',
 'hoarding',
 'important',
 'hygeinic',
 'medical',
 'supplies',
 'like',
 'hand',
 'sanitizer',
 'sterilizing',
 'wipes',
 'importantly',
 'surgical',
 'masks',
 'note',
 'hoarding',
 'behaviors',
 'global',
 'hot',
 'topic',
 'stores',
 'closed',
 'period',
 'time',
 'due',
 'health',
 'concerns',
 'time',
 'store',
 'employees',
 'paid',
 'https',
 'shops',
 'markets',
 'shopping',
 'malls',
 'restaurants',
 'remain',
 'closed',
 'different',
 'cities',
 'pakistan',
 'country',
 'imposed',
 'ban',
 'movement',
 'stop',
 'spread',
 'following',
 'pictures',
 'show',
 'empty',
 'roads',
 'karachi',
 'islamabad',
 'bannu',
 'photos',
 'online',
 'called',
 'supermarket',
 'way',
 'home',
 'generation',
 'used',
 'plenty',
 'instantaneously',
 'time',
 'think',
 'others',
 'adjust',
 'behaviours',
 'lookoutforothers',
 'coronavirus',
 'uk',
 'consumer',
 'diary',
 'studies',
 'coronavirus',
 'https',
 'via',
 'slideshare',
 'went',
 'supermarket',
 'get',
 'food',
 'lady',
 'pushed',
 'get',
 'toilet',
 'paper',
 'coronavirus',
 'making',
 'people',
 'crazy',
 'ask',
 'sprint',
 'customers',
 'coronavirus',
 'layoffs',
 'nounemployment',
 'period',
 'easy',
 'answer',
 'got',
 'text',
 'today',
 'services',
 'getting',
 'shut',
 'make',
 'payment',
 'stock',
 'food',
 'household',
 'necessities',
 'upcoming',
 'quarantine',
 'pay',
 'sprint',
 'crisis',
 'drive',
 'sf',
 'rent',
 'prices',
 'https',
 'https',
 'free',
 'food',
 'event',
 'today',
 'back',
 'popular',
 'demand',
 'thursday',
 'till',
 'noon',
 'check',
 'previous',
 'tweets',
 'link',
 'locations',
 'visit',
 'website',
 'information',
 'reason',
 'country',
 'shortage',
 'ppe',
 'hand',
 'sanitizer',
 'toilet',
 'paper',
 'anything',
 'really',
 'coronavirus',
 'man',
 'arrested',
 'punching',
 'mother',
 'toilet',
 'tissue',
 'paper',
 'link',
 'bio',
 'linkinbio',
 'news',
 'fight',
 'toiletpaper',
 'coronavirus',
 'qurantine',
 'realitytv',
 'gossip',
 'police',
 'arrested',
 'handsanitizer',
 'https',
 'ssupnow',
 'sanitizer',
 'italy',
 'wuhan',
 'grocery',
 'coronavirus',
 'contest',
 'alert',
 'giveawayalert',
 'competition',
 'puzzles',
 'ssupnow',
 'join',
 'guys',
 'drrashiaggarwal',
 'sapnaarathor',
 'tu',
 'video',
 'site',
 'trends',
 'ways',
 'consumers',
 'turning',
 'youtube',
 'help',
 'cope',
 'social',
 'isolation',
 'could',
 'mean',
 'business',
 'thinkwithgoogle',
 'https',
 'video',
 'consumer',
 'behaviour',
 'socialisolation',
 'https',
 'week',
 'home',
 'lockdown',
 'used',
 'raise',
 'response',
 'collecting',
 'toilet',
 'paper',
 'hand',
 'sanitizer',
 'face',
 'masks',
 'visiting',
 'downloading',
 'beta',
 'app',
 'update',
 'worried',
 'drink',
 'turmeric',
 'tea',
 'ginger',
 'lemon',
 'amp',
 'honey',
 'herbal',
 'tea',
 'every',
 'day',
 'without',
 'sugar',
 'get',
 'sainsbury',
 'supermarket',
 'amp',
 'asda',
 'safe',
 'folks',
 'renetrevor',
 'https',
 'bankofamerica',
 'allow',
 'borrowers',
 'pause',
 'mortgage',
 'payments',
 'https',
 'bac',
 'residential',
 'realestate',
 'lender',
 'loans',
 'coronavirus',
 'support',
 'consumer',
 'small',
 'business',
 'clients',
 'homeequity',
 'creditcards',
 'weeks',
 'food',
 'amp',
 'water',
 'refill',
 'prescription',
 'medications',
 'counter',
 'meds',
 'sign',
 'alerts',
 'local',
 'gov',
 'toiletries',
 'hand',
 'sanitizer',
 'first',
 'aid',
 'kit',
 'pet',
 'food',
 'amp',
 'need',
 'stay',
 'home',
 'weeks',
 'longer',
 'see',
 'absolutely',
 'must',
 'make',
 'store',
 'run',
 'time',
 'forget',
 'wear',
 'face',
 'covering',
 'use',
 'proper',
 'hygiene',
 'socialdistancing',
 'https',
 'nstnation',
 'streets',
 'extra',
 'quiet',
 'plenty',
 'parking',
 'spaces',
 'available',
 'shopping',
 'malls',
 'gaya',
 'street',
 'major',
 'city',
 'centre',
 'thoroughfare',
 'deserted',
 'well',
 'https',
 'mco',
 'movementcontrolorder',
 'coronavirus',
 'sabah',
 'clorox',
 'fabric',
 'sanitizer',
 'spray',
 'oz',
 'spray',
 'bottle',
 'https',
 'coronavirus',
 'everyday',
 'make',
 'day',
 'different',
 'color',
 'ice',
 'mocktails',
 'cocktails',
 'minimum',
 'order',
 'stayathome',
 'staysafe',
 'https',
 'businesses',
 'say',
 'trade',
 'war',
 'contributing',
 'shortages',
 'disinfectants',
 'ask',
 'relief',
 'tariffs',
 'steve',
 'ravitz',
 'president',
 'grocery',
 'store',
 'chain',
 'new',
 'jersey',
 'passed',
 'away',
 'due',
 'novel',
 'coronavirus',
 'according',
 'facebook',
 'post',
 'family',
 'member',
 'https',
 'discriminate',
 'society',
 'amp',
 'healthcare',
 'system',
 'minimum',
 'wage',
 'workers',
 'migrant',
 'workers',
 'transported',
 'fields',
 'crowded',
 'trucks',
 'people',
 'living',
 'public',
 'housing',
 'causes',
 'asthma',
 'disproportionately',
 'risk',
 'rapid',
 'falls',
 'petrol',
 'prices',
 'helped',
 'keep',
 'lid',
 'living',
 'costs',
 'last',
 'month',
 'give',
 'first',
 'signs',
 'inflation',
 'slowdown',
 'coronavirus',
 'likely',
 'produce',
 'petrol',
 'fell',
 'litre',
 'february',
 'diesel',
 'dropped',
 'quickly',
 'https',
 'https',
 'non',
 'essential',
 'shops',
 'clchan',
 'yet',
 'every',
 'shopping',
 'channel',
 'still',
 'going',
 'people',
 'really',
 'think',
 'buying',
 'things',
 'thought',
 'people',
 'short',
 'money',
 'work',
 'someone',
 'deliver',
 'stayhomesavelives',
 'stop',
 'buying',
 'crap',
 'need',
 'online',
 'shopping',
 'channels',
 'rajatsharmalive',
 'narendramodi',
 'rajat',
 'jee',
 'ppl',
 'taking',
 'lightly',
 'inspire',
 'efforts',
 'govt',
 'media',
 'civil',
 'society',
 'members',
 'ppl',
 'hurry',
 'open',
 'market',
 'everything',
 'outside',
 'without',
 'thinking',
 'consequences',
 'amids',
 'coronavir',
 'website',
 'includes',
 'page',
 'consumer',
 'resources',
 'featuring',
 'info',
 'legal',
 'services',
 'assistance',
 'available',
 'residents',
 'plus',
 'links',
 'lawyer',
 'referral',
 'service',
 'guidance',
 'attorney',
 'general',
 'office',
 'https',
 'https',
 'every',
 'bank',
 'supermarket',
 'restaurant',
 'rideshare',
 'etc',
 'ever',
 'interacted',
 'sent',
 'emails',
 'responding',
 'peep',
 'insurance',
 'company',
 'though',
 'still',
 'sending',
 'spring',
 'newsletters',
 'even',
 'mention',
 'pandemic',
 'madeinamerica',
 'crazy',
 'aaron',
 'creators',
 'thinkingputty',
 'shifted',
 'production',
 'toys',
 'emergency',
 'hand',
 'sanitizer',
 'municipal',
 'workers',
 'healthcare',
 'facilities',
 'public',
 'utilities',
 'amp',
 'first',
 'responders',
 'gt',
 'https',
 'weknowplay',
 'coronavirus',
 'coronavirus',
 'countdown',
 'grey',
 'lynn',
 'supermarket',
 'turned',
 'online',
 'store',
 'via',
 'nzherald',
 'https',
 'thought',
 'would',
 'helpful',
 'wrote',
 'https',
 'behind',
 'premium',
 'paywall',
 'moment',
 'going',
 'grocery',
 'store',
 'going',
 'pharmacy',
 'everything',
 'keep',
 'family',
 'friends',
 'safe',
 'means',
 'everybody',
 'six',
 'feet',
 'distancing',
 'washing',
 'hands',
 'pushes',
 'many',
 'pple',
 'panic',
 'buy',
 'world',
 'somaliland',
 'gov',
 'issues',
 'warning',
 'local',
 'food',
 'sellers',
 'anyone',
 'food',
 'sellers',
 'caught',
 'raising',
 'food',
 'price',
 'face',
 'justice',
 'amp',
 'business',
 'closed',
 'said',
 'sl',
 ...]

In [ ]:
# @title Tokenize (words with remove punctuation, all lowercase and remove stop words, with speech_tagging)
from nltk import pos_tag

clean_tokens = [
    word.lower()
    for word in clean_tokens
    if word.isalpha() and word.lower() not in stop_words
]

pos_tags = pos_tag(clean_tokens)

print(pos_tags)

[('anyone', 'NN'), ('else', 'RB'), ('keep', 'VB'), ('wondering', 'VBG'), ('would', 'MD'), ('different', 'JJ'), ('hillaryclinton', 'NN'), ('president', 'NN'), ('ran', 'VBD'), ('toilet', 'JJ'), ('paper', 'NN'), ('coronaviruspandemic', 'NN'), ('covid', 'NN'), ('toiletpaper', 'IN'), ('coronavirus', 'NN'), ('https', 'NN'), ('isnt', 'NN'), ('amp', 'NN'), ('food', 'NN'), ('every', 'DT'), ('bluddy', 'NN'), ('supermarket', 'NN'), ('go', 'VBP'), ('lack', 'NN'), ('shoppers', 'NNS'), ('buy', 'VBP'), ('food', 'NN'), ('coronavirus', 'NN'), ('lockdown', 'JJ'), ('went', 'VBD'), ('grocery', 'NN'), ('store', 'NN'), ('essentials', 'NNS'), ('carbohydrates', 'VBZ'), ('little', 'JJ'), ('weird', 'JJ'), ('none', 'NN'), ('usual', 'JJ'), ('milling', 'NN'), ('people', 'NNS'), ('getting', 'VBG'), ('stuff', 'JJ'), ('gtfo', 'NN'), ('grocerystores', 'NNS'), ('socialdistancing', 'VBG'), ('inventory', 'NN'), ('planning', 'NN'), ('name', 'NN'), ('game', 'NN'), ('right', 'RB'), ('packaged', 'VBD'), ('staples', 'NNS'), ('brands', 'NNS'), ('dealing', 'VBG'), ('sudden', 'JJ'), ('surges', 'NNS'), ('demand', 'VBP'), ('owing', 'VBG'), ('try', 'VB'), ('predict', 'NN'), ('long', 'JJ'), ('current', 'JJ'), ('buying', 'NN'), ('patterns', 'NNS'), ('might', 'MD'), ('last', 'JJ'), ('isolation', 'NN'), ('earth', 'NN'), ('ask', 'VB'), ('us', 'PRP'), ('stay', 'VB'), ('home', 'NN'), ('work', 'NN'), ('food', 'NN'), ('money', 'NN'), ('stock', 'NN'), ('house', 'NN'), ('naija', 'JJ'), ('hmmmmm', 'NN'), ('body', 'NN'), ('crying', 'VBG'), ('pls', 'JJ'), ('pls', 'NN'), ('hear', 'VBP'), ('cry', 'NN'), ('need', 'VBP'), ('money', 'NN'), ('isolation', 'NN'), ('thing', 'NN'), ('work', 'NN'), ('make', 'VBP'), ('come', 'JJ'), ('isolate', 'NN'), ('die', 'NN'), ('hunger', 'NN'), ('donjazzy', 'NN'), ('iruntow', 'NN'), ('went', 'VBD'), ('grocery', 'RB'), ('elderly', 'RB'), ('headed', 'VBN'), ('back', 'RP'), ('home', 'NN'), ('removed', 'VBD'), ('outside', 'JJ'), ('hit', 'NN'), ('grocery', 'NN'), ('store', 'NN'), ('controlled', 'VBD'), ('line', 'NN'), ('havin', 'NN'), ('handful', 'NN'), ('avail', 'NN'), ('n', 'JJ'), ('turn', 'NN'), ('shop', 'NN'), ('helped', 'VBD'), ('soc', 'VB'), ('impact', 'JJ'), ('coronavirus', 'NN'), ('singapore', 'NN'), ('private', 'JJ'), ('home', 'NN'), ('prices', 'NNS'), ('https', 'VBD'), ('believe', 'VBP'), ('gone', 'VBN'), ('order', 'NN'), ('tesco', 'NN'), ('online', 'NN'), ('shopping', 'NN'), ('single', 'JJ'), ('pack', 'NN'), ('fresh', 'JJ'), ('chicken', 'NN'), ('along', 'IN'), ('pasta', 'JJ'), ('toilet', 'NN'), ('roll', 'NN'), ('hand', 'NN'), ('soap', 'NN'), ('believe', 'VBP'), ('coronavirus', 'NN'), ('shown', 'VBN'), ('grotesque', 'JJ'), ('side', 'NN'), ('society', 'NN'), ('greedy', 'NN'), ('selfish', 'JJ'), ('bastards', 'NNS'), ('coronavirusuk', 'NN'), ('past', 'IN'), ('week', 'NN'), ('stories', 'NNS'), ('america', 'VBP'), ('show', 'NN'), ('farmers', 'NNS'), ('dumping', 'VBG'), ('milk', 'NN'), ('plowing', 'VBG'), ('crops', 'NNS'), ('normal', 'JJ'), ('demand', 'NN'), ('shifts', 'NNS'), ('look', 'VBP'), ('hungry', 'JJ'), ('americans', 'NNS'), ('without', 'IN'), ('incomes', 'NNS'), ('fed', 'VBP'), ('govt', 'JJ'), ('failing', 'NN'), ('americans', 'NNS'), ('survive', 'VBP'), ('must', 'MD'), ('face', 'VB'), ('food', 'NN'), ('shortages', 'NNS'), ('next', 'IN'), ('kellyo', 'NN'), ('nygovcuomo', 'IN'), ('canada', 'JJ'), ('competition', 'NN'), ('bureau', 'NN'), ('prepared', 'VBD'), ('pursue', 'NN'), ('cases', 'NNS'), ('price', 'NN'), ('gouging', 'VBG'), ('https', 'NN'), ('declaring', 'VBG'), ('state', 'NN'), ('emergency', 'NN'), ('ontario', 'NN'), ('power', 'NN'), ('freeze', 'NN'), ('prices', 'NNS'), ('fuel', 'NN'), ('thought', 'VBN'), ('crudeoil', 'NN'), ('prices', 'NNS'), ('corrected', 'VBD'), ('almost', 'RB'), ('since', 'IN'), ('dec', 'NN'), ('result', 'NN'), ('crisis', 'NN'), ('one', 'CD'), ('largest', 'JJS'), ('oil', 'NN'), ('importers', 'NNS'), ('world', 'NN'), ('india', 'NN'), ('imports', 'NNS'), ('around', 'IN'), ('oil', 'NN'), ('demand', 'NN'), ('coronanews', 'NN'), ('hungarian', 'JJ'), ('oil', 'NN'), ('gas', 'NN'), ('company', 'NN'), ('mol', 'NN'), ('switched', 'VBD'), ('production', 'NN'), ('line', 'NN'), ('sanitizers', 'NNS'), ('made', 'VBD'), ('earlier', 'RBR'), ('windshield', 'JJ'), ('cleaner', 'JJR'), ('fluid', 'JJ'), ('hungary', 'JJ'), ('mol', 'NN'), ('sanitizer', 'NN'), ('coronavirus', 'NN'), ('read', 'VBD'), ('https', 'JJ'), ('picture', 'NN'), ('https', 'NN'), ('recently', 'RB'), ('seen', 'VBN'), ('increase', 'NN'), ('people', 'NNS'), ('shopping', 'VBG'), ('online', 'JJ'), ('short', 'JJ'), ('term', 'NN'), ('impact', 'NN'), ('serve', 'VBP'), ('customers', 'NNS'), ('notice', 'RB'), ('currently', 'RB'), ('stock', 'NN'), ('brands', 'NNS'), ('amp', 'JJ'), ('items', 'NNS'), ('household', 'VBD'), ('staples', 'NNS'), ('categories', 'NNS'), ('https', 'VBP'), ('panic', 'JJ'), ('mode', 'NN'), ('yet', 'RB'), ('would', 'MD'), ('suggest', 'VB'), ('food', 'NN'), ('tanks', 'NNS'), ('street', 'NN'), ('right', 'RB'), ('even', 'RB'), ('know', 'VBP'), ('anymore', 'RB'), ('trust', 'JJ'), ('coronavirus', 'NN'), ('good', 'JJ'), ('evening', 'NN'), ('lovelies', 'NNS'), ('hope', 'VBP'), ('well', 'RB'), ('day', 'NN'), ('dull', 'JJ'), ('online', 'NN'), ('shopping', 'NN'), ('amazonuk', 'NN'), ('chilled', 'VBD'), ('xx', 'JJ'), ('thearchers', 'NNS'), ('coronavirus', 'VBP'), ('anyone', 'NN'), ('experienced', 'VBD'), ('getting', 'VBG'), ('headaches', 'NNS'), ('even', 'RB'), ('slight', 'VBD'), ('shopping', 'VBG'), ('grocery', 'NN'), ('store', 'NN'), ('full', 'JJ'), ('shoppers', 'NNS'), ('socialdistancing', 'VBG'), ('theory', 'NN'), ('suggests', 'VBZ'), ('buildings', 'NNS'), ('properly', 'RB'), ('ventilated', 'VBN'), ('allow', 'NN'), ('contaminated', 'VBN'), ('air', 'NN'), ('breath', 'NN'), ('shoppers', 'NNS'), ('dissipate', 'VBP'), ('day', 'NN'), ('still', 'RB'), ('needed', 'VBN'), ('go', 'VBP'), ('supermarket', 'NN'), ('wrong', 'JJ'), ('coronavirus', 'NN'), ('cdnpoli', 'NNS'), ('uspoli', 'JJ'), ('coronavirus', 'VBP'), ('coronaviruspandemic', 'JJ'), ('vicki', 'NN'), ('today', 'NN'), ('supermarket', 'VBP'), ('toilet', 'NN'), ('paper', 'NN'), ('wrapped', 'VBD'), ('totally', 'RB'), ('clear', 'JJ'), ('plastic', 'NN'), ('printing', 'NN'), ('whatsoever', 'JJ'), ('figure', 'NN'), ('paper', 'NN'), ('made', 'VBN'), ('crushed', 'JJ'), ('sandpap', 'JJ'), ('live', 'JJ'), ('area', 'NN'), ('work', 'NN'), ('get', 'VBP'), ('supermarket', 'JJ'), ('dm', 'JJ'), ('let', 'NN'), ('know', 'VB'), ('need', 'VB'), ('deliver', 'RB'), ('home', 'NN'), ('shift', 'NN'), ('fighting', 'VBG'), ('ashamed', 'JJ'), ('part', 'NN'), ('city', 'NN'), ('right', 'RB'), ('seeing', 'VBG'), ('much', 'JJ'), ('evidence', 'NN'), ('together', 'RB'), ('coronavirus', 'NN'), ('stophoarding', 'VBG'), ('panicbuyinguk', 'JJ'), ('london', 'JJ'), ('part', 'NN'), ('consumer', 'NN'), ('coronavirus', 'NN'), ('response', 'NN'), ('also', 'RB'), ('saw', 'VBD'), ('early', 'JJ'), ('hoarding', 'NN'), ('important', 'JJ'), ('hygeinic', 'JJ'), ('medical', 'JJ'), ('supplies', 'NNS'), ('like', 'IN'), ('hand', 'NN'), ('sanitizer', 'NN'), ('sterilizing', 'VBG'), ('wipes', 'NNS'), ('importantly', 'RB'), ('surgical', 'JJ'), ('masks', 'NNS'), ('note', 'VBP'), ('hoarding', 'VBG'), ('behaviors', 'NNS'), ('global', 'JJ'), ('hot', 'JJ'), ('topic', 'NN'), ('stores', 'NNS'), ('closed', 'VBD'), ('period', 'NN'), ('time', 'NN'), ('due', 'JJ'), ('health', 'NN'), ('concerns', 'NNS'), ('time', 'NN'), ('store', 'NN'), ('employees', 'NNS'), ('paid', 'VBD'), ('https', 'JJ'), ('shops', 'NNS'), ('markets', 'NNS'), ('shopping', 'VBG'), ('malls', 'NNS'), ('restaurants', 'NNS'), ('remain', 'VBP'), ('closed', 'JJ'), ('different', 'JJ'), ('cities', 'NNS'), ('pakistan', 'VBP'), ('country', 'NN'), ('imposed', 'VBN'), ('ban', 'JJ'), ('movement', 'NN'), ('stop', 'VB'), ('spread', 'NN'), ('following', 'VBG'), ('pictures', 'NNS'), ('show', 'VBP'), ('empty', 'JJ'), ('roads', 'NNS'), ('karachi', 'VBP'), ('islamabad', 'JJ'), ('bannu', 'NN'), ('photos', 'NNS'), ('online', 'VBP'), ('called', 'VBN'), ('supermarket', 'NN'), ('way', 'NN'), ('home', 'NN'), ('generation', 'NN'), ('used', 'VBD'), ('plenty', 'RB'), ('instantaneously', 'JJ'), ('time', 'NN'), ('think', 'VBP'), ('others', 'NNS'), ('adjust', 'VBP'), ('behaviours', 'NN'), ('lookoutforothers', 'NNS'), ('coronavirus', 'VBP'), ('uk', 'JJ'), ('consumer', 'NN'), ('diary', 'JJ'), ('studies', 'NNS'), ('coronavirus', 'VBP'), ('https', 'JJ'), ('via', 'IN'), ('slideshare', 'NN'), ('went', 'VBD'), ('supermarket', 'NN'), ('get', 'VB'), ('food', 'NN'), ('lady', 'NN'), ('pushed', 'VBD'), ('get', 'VB'), ('toilet', 'JJ'), ('paper', 'NN'), ('coronavirus', 'NN'), ('making', 'VBG'), ('people', 'NNS'), ('crazy', 'JJ'), ('ask', 'JJ'), ('sprint', 'NN'), ('customers', 'NNS'), ('coronavirus', 'VBP'), ('layoffs', 'JJ'), ('nounemployment', 'JJ'), ('period', 'NN'), ('easy', 'JJ'), ('answer', 'NN'), ('got', 'VBD'), ('text', 'RB'), ('today', 'NN'), ('services', 'NNS'), ('getting', 'VBG'), ('shut', 'JJ'), ('make', 'VBP'), ('payment', 'NN'), ('stock', 'NN'), ('food', 'NN'), ('household', 'NN'), ('necessities', 'NNS'), ('upcoming', 'VBG'), ('quarantine', 'JJ'), ('pay', 'NN'), ('sprint', 'NN'), ('crisis', 'NN'), ('drive', 'NN'), ('sf', 'NN'), ('rent', 'NN'), ('prices', 'NNS'), ('https', 'VBP'), ('https', 'JJ'), ('free', 'JJ'), ('food', 'NN'), ('event', 'NN'), ('today', 'NN'), ('back', 'RB'), ('popular', 'JJ'), ('demand', 'NN'), ('thursday', 'NN'), ('till', 'VB'), ('noon', 'RB'), ('check', 'VBP'), ('previous', 'JJ'), ('tweets', 'NNS'), ('link', 'VBP'), ('locations', 'NNS'), ('visit', 'VBP'), ('website', 'JJ'), ('information', 'NN'), ('reason', 'NN'), ('country', 'NN'), ('shortage', 'NN'), ('ppe', 'JJ'), ('hand', 'NN'), ('sanitizer', 'NN'), ('toilet', 'NN'), ('paper', 'NN'), ('anything', 'NN'), ('really', 'RB'), ('coronavirus', 'JJ'), ('man', 'NN'), ('arrested', 'VBD'), ('punching', 'VBG'), ('mother', 'NN'), ('toilet', 'NN'), ('tissue', 'NN'), ('paper', 'NN'), ('link', 'NN'), ('bio', 'IN'), ('linkinbio', 'JJ'), ('news', 'NN'), ('fight', 'NN'), ('toiletpaper', 'IN'), ('coronavirus', 'NN'), ('qurantine', 'NN'), ('realitytv', 'NN'), ('gossip', 'NN'), ('police', 'NN'), ('arrested', 'VBD'), ('handsanitizer', 'NN'), ('https', 'NN'), ('ssupnow', 'VBP'), ('sanitizer', 'NN'), ('italy', 'NN'), ('wuhan', 'JJ'), ('grocery', 'NN'), ('coronavirus', 'NN'), ('contest', 'NN'), ('alert', 'NN'), ('giveawayalert', 'JJ'), ('competition', 'NN'), ('puzzles', 'NNS'), ('ssupnow', 'VBP'), ('join', 'NN'), ('guys', 'NNS'), ('drrashiaggarwal', 'VBP'), ('sapnaarathor', 'NN'), ('tu', 'NN'), ('video', 'NN'), ('site', 'NN'), ('trends', 'NNS'), ('ways', 'NNS'), ('consumers', 'NNS'), ('turning', 'VBG'), ('youtube', 'NN'), ('help', 'NN'), ('cope', 'VB'), ('social', 'JJ'), ('isolation', 'NN'), ('could', 'MD'), ('mean', 'VB'), ('business', 'NN'), ('thinkwithgoogle', 'NN'), ('https', 'NN'), ('video', 'NN'), ('consumer', 'NN'), ('behaviour', 'NN'), ('socialisolation', 'NN'), ('https', 'NN'), ('week', 'NN'), ('home', 'NN'), ('lockdown', 'NN'), ('used', 'VBN'), ('raise', 'NN'), ('response', 'NN'), ('collecting', 'VBG'), ('toilet', 'JJ'), ('paper', 'NN'), ('hand', 'NN'), ('sanitizer', 'VBD'), ('face', 'NN'), ('masks', 'NNS'), ('visiting', 'VBG'), ('downloading', 'VBG'), ('beta', 'NN'), ('app', 'NN'), ('update', 'NN'), ('worried', 'VBD'), ('drink', 'JJ'), ('turmeric', 'JJ'), ('tea', 'NN'), ('ginger', 'NN'), ('lemon', 'JJ'), ('amp', 'NN'), ('honey', 'NN'), ('herbal', 'JJ'), ('tea', 'NN'), ('every', 'DT'), ('day', 'NN'), ('without', 'IN'), ('sugar', 'NN'), ('get', 'VBP'), ('sainsbury', 'NN'), ('supermarket', 'NN'), ('amp', 'NN'), ('asda', 'NN'), ('safe', 'JJ'), ('folks', 'NNS'), ('renetrevor', 'VBP'), ('https', 'NN'), ('bankofamerica', 'NN'), ('allow', 'IN'), ('borrowers', 'NNS'), ('pause', 'VBP'), ('mortgage', 'NN'), ('payments', 'NNS'), ('https', 'VBP'), ('bac', 'JJ'), ('residential', 'JJ'), ('realestate', 'NN'), ('lender', 'NN'), ('loans', 'NNS'), ('coronavirus', 'VBP'), ('support', 'JJ'), ('consumer', 'NN'), ('small', 'JJ'), ('business', 'NN'), ('clients', 'NNS'), ('homeequity', 'NN'), ('creditcards', 'NNS'), ('weeks', 'NNS'), ('food', 'NN'), ('amp', 'JJ'), ('water', 'NN'), ('refill', 'NN'), ('prescription', 'NN'), ('medications', 'NNS'), ('counter', 'VBP'), ('meds', 'NNS'), ('sign', 'NN'), ('alerts', 'VBZ'), ('local', 'JJ'), ('gov', 'NN'), ('toiletries', 'NNS'), ('hand', 'NN'), ('sanitizer', 'NN'), ('first', 'RB'), ('aid', 'JJ'), ('kit', 'NN'), ('pet', 'NN'), ('food', 'NN'), ('amp', 'NN'), ('need', 'VBP'), ('stay', 'VB'), ('home', 'NN'), ('weeks', 'NNS'), ('longer', 'RBR'), ('see', 'VBP'), ('absolutely', 'RB'), ('must', 'MD'), ('make', 'VB'), ('store', 'NN'), ('run', 'NN'), ('time', 'NN'), ('forget', 'NN'), ('wear', 'JJ'), ('face', 'NN'), ('covering', 'VBG'), ('use', 'JJ'), ('proper', 'JJ'), ('hygiene', 'NN'), ('socialdistancing', 'VBG'), ('https', 'JJ'), ('nstnation', 'NN'), ('streets', 'NNS'), ('extra', 'VBP'), ('quiet', 'JJ'), ('plenty', 'NN'), ('parking', 'NN'), ('spaces', 'NNS'), ('available', 'JJ'), ('shopping', 'NN'), ('malls', 'NNS'), ('gaya', 'VBP'), ('street', 'NN'), ('major', 'JJ'), ('city', 'NN'), ('centre', 'NN'), ('thoroughfare', 'NN'), ('deserted', 'VBN'), ('well', 'RB'), ('https', 'JJ'), ('mco', 'NNS'), ('movementcontrolorder', 'VBP'), ('coronavirus', 'NN'), ('sabah', 'NN'), ('clorox', 'NN'), ('fabric', 'JJ'), ('sanitizer', 'NN'), ('spray', 'NN'), ('oz', 'NN'), ('spray', 'NN'), ('bottle', 'NN'), ('https', 'NN'), ('coronavirus', 'NN'), ('everyday', 'JJ'), ('make', 'VBP'), ('day', 'NN'), ('different', 'JJ'), ('color', 'NN'), ('ice', 'NN'), ('mocktails', 'NNS'), ('cocktails', 'VBP'), ('minimum', 'JJ'), ('order', 'NN'), ('stayathome', 'NN'), ('staysafe', 'JJ'), ('https', 'NN'), ('businesses', 'NNS'), ('say', 'VBP'), ('trade', 'NN'), ('war', 'NN'), ('contributing', 'VBG'), ('shortages', 'NNS'), ('disinfectants', 'NNS'), ('ask', 'VBP'), ('relief', 'JJ'), ('tariffs', 'NNS'), ('steve', 'VBP'), ('ravitz', 'NN'), ('president', 'NN'), ('grocery', 'NN'), ('store', 'NN'), ('chain', 'NN'), ('new', 'JJ'), ('jersey', 'NN'), ('passed', 'VBN'), ('away', 'RB'), ('due', 'JJ'), ('novel', 'NN'), ('coronavirus', 'NN'), ('according', 'VBG'), ('facebook', 'NN'), ('post', 'NN'), ('family', 'NN'), ('member', 'NN'), ('https', 'NN'), ('discriminate', 'NN'), ('society', 'NN'), ('amp', 'NN'), ('healthcare', 'NN'), ('system', 'NN'), ('minimum', 'JJ'), ('wage', 'NN'), ('workers', 'NNS'), ('migrant', 'JJ'), ('workers', 'NNS'), ('transported', 'VBD'), ('fields', 'NNS'), ('crowded', 'VBD'), ('trucks', 'NNS'), ('people', 'NNS'), ('living', 'VBG'), ('public', 'JJ'), ('housing', 'NN'), ('causes', 'NNS'), ('asthma', 'VBP'), ('disproportionately', 'RB'), ('risk', 'JJ'), ('rapid', 'JJ'), ('falls', 'NNS'), ('petrol', 'NN'), ('prices', 'NNS'), ('helped', 'VBD'), ('keep', 'VB'), ('lid', 'JJ'), ('living', 'NN'), ('costs', 'NNS'), ('last', 'JJ'), ('month', 'NN'), ('give', 'VBD'), ('first', 'JJ'), ('signs', 'NNS'), ('inflation', 'NN'), ('slowdown', 'NN'), ('coronavirus', 'NN'), ('likely', 'JJ'), ('produce', 'NN'), ('petrol', 'NN'), ('fell', 'VBD'), ('litre', 'RB'), ('february', 'JJ'), ('diesel', 'NN'), ('dropped', 'VBD'), ('quickly', 'RB'), ('https', 'JJ'), ('https', 'NN'), ('non', 'JJ'), ('essential', 'JJ'), ('shops', 'NNS'), ('clchan', 'VBP'), ('yet', 'RB'), ('every', 'DT'), ('shopping', 'NN'), ('channel', 'NN'), ('still', 'RB'), ('going', 'VBG'), ('people', 'NNS'), ('really', 'RB'), ('think', 'VBP'), ('buying', 'VBG'), ('things', 'NNS'), ('thought', 'VBN'), ('people', 'NNS'), ('short', 'JJ'), ('money', 'NN'), ('work', 'NN'), ('someone', 'NN'), ('deliver', 'WDT'), ('stayhomesavelives', 'NNS'), ('stop', 'VBP'), ('buying', 'VBG'), ('crap', 'NN'), ('need', 'VBP'), ('online', 'JJ'), ('shopping', 'NN'), ('channels', 'NNS'), ('rajatsharmalive', 'VBP'), ('narendramodi', 'JJ'), ('rajat', 'NN'), ('jee', 'NN'), ('ppl', 'NN'), ('taking', 'VBG'), ('lightly', 'RB'), ('inspire', 'VB'), ('efforts', 'NNS'), ('govt', 'JJ'), ('media', 'NNS'), ('civil', 'JJ'), ('society', 'NN'), ('members', 'NNS'), ('ppl', 'VBP'), ('hurry', 'JJ'), ('open', 'JJ'), ('market', 'NN'), ('everything', 'NN'), ('outside', 'IN'), ('without', 'IN'), ('thinking', 'VBG'), ('consequences', 'NNS'), ('amids', 'NNS'), ('coronavir', 'VBP'), ('website', 'JJ'), ('includes', 'VBZ'), ('page', 'JJ'), ('consumer', 'NN'), ('resources', 'NNS'), ('featuring', 'VBG'), ('info', 'JJ'), ('legal', 'JJ'), ('services', 'NNS'), ('assistance', 'NN'), ('available', 'JJ'), ('residents', 'NNS'), ('plus', 'CC'), ('links', 'NNS'), ('lawyer', 'NN'), ('referral', 'JJ'), ('service', 'NN'), ('guidance', 'NN'), ('attorney', 'NN'), ('general', 'JJ'), ('office', 'NN'), ('https', 'NN'), ('https', 'NN'), ('every', 'DT'), ('bank', 'NN'), ('supermarket', 'NN'), ('restaurant', 'NN'), ('rideshare', 'NN'), ('etc', 'FW'), ('ever', 'RB'), ('interacted', 'VBN'), ('sent', 'NN'), ('emails', 'NNS'), ('responding', 'VBG'), ('peep', 'JJ'), ('insurance', 'NN'), ('company', 'NN'), ('though', 'IN'), ('still', 'RB'), ('sending', 'VBG'), ('spring', 'NN'), ('newsletters', 'NNS'), ('even', 'RB'), ('mention', 'VBP'), ('pandemic', 'JJ'), ('madeinamerica', 'NN'), ('crazy', 'JJ'), ('aaron', 'NN'), ('creators', 'NNS'), ('thinkingputty', 'RB'), ('shifted', 'VBD'), ('production', 'NN'), ('toys', 'NN'), ('emergency', 'NN'), ('hand', 'NN'), ('sanitizer', 'NN'), ('municipal', 'JJ'), ('workers', 'NNS'), ('healthcare', 'JJ'), ('facilities', 'NNS'), ('public', 'JJ'), ('utilities', 'NNPS'), ('amp', 'VBP'), ('first', 'JJ'), ('responders', 'NNS'), ('gt', 'VBP'), ('https', 'JJ'), ('weknowplay', 'NN'), ('coronavirus', 'NN'), ('coronavirus', 'NN'), ('countdown', 'JJ'), ('grey', 'NN'), ('lynn', 'NN'), ('supermarket', 'NN'), ('turned', 'VBD'), ('online', 'JJ'), ('store', 'NN'), ('via', 'IN'), ('nzherald', 'JJ'), ('https', 'NN'), ('thought', 'NN'), ('would', 'MD'), ('helpful', 'VB'), ('wrote', 'VBD'), ('https', 'NN'), ('behind', 'IN'), ('premium', 'JJ'), ('paywall', 'JJ'), ('moment', 'NN'), ('going', 'VBG'), ('grocery', 'NN'), ('store', 'NN'), ('going', 'VBG'), ('pharmacy', 'NN'), ('everything', 'NN'), ('keep', 'VB'), ('family', 'NN'), ('friends', 'NNS'), ('safe', 'JJ'), ('means', 'VBZ'), ('everybody', 'NN'), ('six', 'CD'), ('feet', 'NNS'), ('distancing', 'VBG'), ('washing', 'VBG'), ('hands', 'NNS'), ('pushes', 'NNS'), ('many', 'JJ'), ('pple', 'JJ'), ('panic', 'JJ'), ('buy', 'NN'), ('world', 'NN'), ('somaliland', 'VBP'), ('gov', 'NN'), ('issues', 'NNS'), ('warning', 'VBG'), ('local', 'JJ'), ('food', 'NN'), ('sellers', 'NNS'), ('anyone', 'NN'), ('food', 'NN'), ('sellers', 'NNS'), ('caught', 'VBD'), ('raising', 'VBG'), ('food', 'NN'), ('price', 'NN'), ('face', 'NN'), ('justice', 'NN'), ('amp', 'NN'), ('business', 'NN'), ('closed', 'VBD'), ('said', 'VBD'), ('sl', 'JJ'), ('interior', 'JJ'), ('minister', 'NN'), ('mohamed', 'VBD'), ('kaahin', 'JJ'), ('https', 'JJ'), ('price', 'NN'), ('transparency', 'NN'), ('important', 'JJ'), ('people', 'NNS'), ('country', 'NN'), ('many', 'JJ'), ('ways', 'NNS'), ('prove', 'VBP'), ('important', 'JJ'), ('healthcare', 'NN'), ('great', 'JJ'), ('issue', 'NN'), ('republicans', 'VBZ'), ('democrats', 'NNPS'), ('hopefully', 'RB'), ('approved', 'VBD'), ('fall', 'JJ'), ('demand', 'NN'), ('everything', 'NN'), ('food', 'NN'), ('fuel', 'NN'), ('coronavirus', 'NN'), ('means', 'VBZ'), ('storage', 'JJ'), ('space', 'NN'), ('selling', 'VBG'), ('premium', 'JJ'), ('commodities', 'NNS'), ('storage', 'VBP'), ('logistics', 'NNS'), ('trade', 'NN'), ('oil', 'NN'), ('food', 'NN'), ('https', 'NN'), ('people', 'NNS'), ('hospital', 'VBP'), ('scared', 'JJ'), ('dying', 'VBG'), ('alone', 'RB'), ('coronavirus', 'NN'), ('people', 'NNS'), ('still', 'RB'), ('going', 'VBG'), ('around', 'IN'), ('mean', 'JJ'), ('others', 'NNS'), ('running', 'VBG'), ('scams', 'JJ'), ('jacking', 'VBG'), ('prices', 'NNS'), ('toilet', 'NN'), ('tissue', 'NN'), ('hand', 'NN'), ('sanitizer', 'NN'), ('sad', 'NN'), ('messed', 'VBD'), ('human', 'JJ'), ('beings', 'NNS'), ('wooglobe', 'VBP'), ('coronavirus', 'NN'), ('pandemic', 'JJ'), ('last', 'JJ'), ('toilet', 'NN'), ('paper', 'NN'), ('wooglobe', 'N

### Data Cleaning for Text Similarity

In [ ]:
# dropping na rows

data.dropna(subset=['OriginalTweet'], inplace=True)

In [ ]:
# lowercasing

data.OriginalTweet = data.OriginalTweet.str.lower()

In [ ]:
import re

def remove_noise(text):
    text = re.sub(r'http\S+', '', text)        # remove URLs
    text = re.sub(r'[^a-zA-Z\s]', '', text)   # remove numbers & special chars
    text = re.sub(r'\s+', ' ', text).strip()  # remove extra whitespace
    return text

data.OriginalTweet = data.OriginalTweet.apply(remove_noise)

In [ ]:
# Tokenize
data['tokens'] = data.OriginalTweet.apply(word_tokenize)

## Loading the Data

In [ ]:
# @title Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(data['OriginalTweet']).toarray()

cv_df = pd.DataFrame(X, columns=cv.get_feature_names_out())
cv_df.head()

,aapl,aarons,abandons,abc,abcactionnews,abdulaziz,abhishekiplfeak,abideth,abili,able,...,youve,yrs,zachary,zakat,zation,zionists,zombie,zombieland,zombies,zoomupyourlife
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# @title TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(data['OriginalTweet']).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out())
dt_tfidf.head()

,aapl,aarons,abandons,abc,abcactionnews,abdulaziz,abhishekiplfeak,abideth,abili,able,...,youve,yrs,zachary,zakat,zation,zionists,zombie,zombieland,zombies,zoomupyourlife
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

In [ ]:

from itertools import combinations

pairs = list(combinations(data.OriginalTweet.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(data)), 2)) # all index combos starting with (0,1)
song_pairs = [(data.OriginalTweet[a_index], data.OriginalTweet[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('anyone else keep wondering how it would be different if hillaryclinton were president',
  'ran out of toilet paper coronaviruspandemic covid toiletpaper coronavirus'),
 ('anyone else keep wondering how it would be different if hillaryclinton were president',
  'this isnt just mamps food this is every bluddy supermarket you go to lack of shoppers to buy food coronavirus corvid lockdown'),
 ('anyone else keep wondering how it would be different if hillaryclinton were president',
  'just went to the grocery store for essentials carbohydrates and it was a little weird none of the usual milling just people getting their stuff and gtfo covid grocerystores socialdistancing'),
 ('anyone else keep wondering how it would be different if hillaryclinton were president',
  'inventory planning is the name of the game right now in packaged staples as brands dealing with sudden surges in demand owing to try to predict how long current buying patterns might last'),
 ('anyone else keep wondering how it would be different if hillaryclinton were president',
  'covid isolation how on earth will you ask us to stay at home no work no food no money to stock the housenaija hmmmmm if no body is crying out pls and pls o hear my cry o i need money so the isolation thing can work o make i come isolate die of hunger donjazzy iruntow')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [ ]:

results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8571593913749195),
  ('coronavirus how to avoid fraudsters during covid outbreak coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus supermarket shoppers keep calm and queue coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow')),
 (np.float64(0.8164965809277259),
  ('toilet paper', 'part no toilet paper don t do this')),
 (np.float64(0.7826237921249265),
  ('i applied and got a job three hours later supermarkets hire coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus how to avoid fraudsters during covid outbreak coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow')),
 (np.float64(0.7500000000000001),
  ('i applied and got a job three hours later supermarkets hire coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus supermarket shoppers keep calm and queue coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow')),
 (np.float64(0.75),
  ('everyone in the grocery store businessthank you coronavirus',
   'in the front of the grocery store any takers coronavirus'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [ ]:

results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.7518806081016839),
  ('toilet paper', 'part no toilet paper don t do this')),
 (np.float64(0.7358289911823394),
  ('coronavirus how to avoid fraudsters during covid outbreak coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus supermarket shoppers keep calm and queue coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow')),
 (np.float64(0.6466003187610132),
  ('un world foodprices fall sharply in march because of coronavirus',
   'world food prices fall sharply in march because of coronavirus oil slump un')),
 (np.float64(0.6343382539732909),
  ('i applied and got a job three hours later supermarkets hire coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus how to avoid fraudsters during covid outbreak coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow')),
 (np.float64(0.624179919479557),
  ('i applied and got a job three hours later supermarkets hire coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow',
   'coronavirus supermarket shoppers keep calm and queue coronavirus covid covid covid corona coronavirusoutbreak prepper survival bushcraft rt follow'))]

# Conclusion

> In this lab activity, we were tasked to do text similarity using Count Vecotrizer and TF-IDF. What I have learned is that before doing any NLP Text Similarity, we need to preprocess the data for the NLP models. The procedures shows us how to remove special characters and remove other unnecessary data that can increase the load to the model. In the supplmentary activity, I used a Tweets about or related to Corona Virus. I extracted the data and only used 1,000 datapoints due to its big data. Whenever I used the full 40,0000 datapoints, the RAM usage in Google Colab is consumed befoe even finishing the loading of the data into the NLP models. Then, I cleaned the data by removing special characters, non alpha characters, and URLs. After cleaning the data, I loaded the data into the two models and used Cosine Distance Similarity to check the pairs that are similar to one another. Based on the output, Count Vectorizer has the highest top 5 pair accuracies. Even basing it on the output, I can tell that the top 5 texts were similar. Overall, this lab activity introduced me to the concpet of NLP models.